name = "rober-m/aiken-plutus-v3"
version = "0.0.0"
compiler = "v1.1.1"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'rober-m/aiken-plutus-v3'"

[repository]
user = "rober-m"
project = "aiken-plutus-v3"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[config]
